<a href="https://colab.research.google.com/github/VysakhVasudevan/intro-to-python-/blob/main/pandaaa.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import files
supermarket=files.upload()

Saving Supermarket_sales.csv to Supermarket_sales (1).csv


In [ ]:
from google.colab import files
leagues=files.upload()

Saving teams_and_leagues.csv to teams_and_leagues.csv


In [ ]:
import pandas

In [ ]:
teamgoals={
    'teams' : ['Spain' , 'England' ],
    'goals' : [2,4]
}
teamgoaldf= pandas.DataFrame(teamgoals)
print(teamgoaldf)

     teams  goals
0    Spain      2
1  England      4


In [ ]:
PlayerNationalities={
    'Players'   : ['Messi' , 'Reus']
    'goals' : [2,4]
}
playercountriesdf= pandas.DataFrame(PlayerNationalities)
print(playercountriesdf)

SyntaxError: ignored

In [ ]:
playercountries={
    'player' : ['Messi' , 'Reus' ],
    'countries' : ['Argentina', 'Germany']
}
playernationalities= pandas.DataFrame(playercountries)
print(playernationalities)

  player  countries
0  Messi  Argentina
1   Reus    Germany


In [ ]:
subjectmarks={
    'subject' : ['English' , 'Maths'],
    'marks' : [29 , 35]
}
subjectmarksdf=pandas.DataFrame(subjectmarks)
print(subjectmarksdf)


   subject  marks
0  English     29
1    Maths     35


In [ ]:
import pandas
dataframe=pandas.read_csv('Supermarket_sales.csv')
print(dataframe)

       No    InvoiceID Branch       City Customertype  Gender  \
0       1  750-67-8428      A     Yangon       Member  Female   
1       2  226-31-3081      C  Naypyitaw       Normal  Female   
2       3  631-41-3108      A     Yangon       Normal    Male   
3       4  123-19-1176      A     Yangon       Member    Male   
4       5  373-73-7910      A     Yangon       Normal    Male   
..    ...          ...    ...        ...          ...     ...   
995   996  233-67-5758      C  Naypyitaw       Normal    Male   
996   997  303-96-2227      B   Mandalay       Normal  Female   
997   998  727-02-1313      A     Yangon       Member    Male   
998   999  347-56-2442      A     Yangon       Normal    Male   
999  1000  849-09-3807      A     Yangon       Member  Female   

                Productline  Unitprice  Quantity      Tax      Total  \
0         Health and beauty      74.69         7  26.1415   548.9715   
1    Electronic accessories      15.28         5   3.8200    80.2200   
2  

In [ ]:
print(dataframe.head())

   No    InvoiceID Branch       City Customertype  Gender  \
0   1  750-67-8428      A     Yangon       Member  Female   
1   2  226-31-3081      C  Naypyitaw       Normal  Female   
2   3  631-41-3108      A     Yangon       Normal    Male   
3   4  123-19-1176      A     Yangon       Member    Male   
4   5  373-73-7910      A     Yangon       Normal    Male   

              Productline  Unitprice  Quantity      Tax     Total       Date  \
0       Health and beauty      74.69         7  26.1415  548.9715   1/5/2019   
1  Electronic accessories      15.28         5   3.8200   80.2200   3/8/2019   
2      Home and lifestyle      46.33         7  16.2155  340.5255   3/3/2019   
3       Health and beauty      58.22         8  23.2880  489.0480  1/27/2019   
4       Sports and travel      86.31         7  30.2085  634.3785   2/8/2019   

    Time      Payment    cogs  gross_margin_percentage  gross_iincome  Rating  
0  13:08      Ewallet  522.83                 4.761905        26.1415   

In [ ]:
print(dataframe.tail())

       No    InvoiceID Branch       City Customertype  Gender  \
995   996  233-67-5758      C  Naypyitaw       Normal    Male   
996   997  303-96-2227      B   Mandalay       Normal  Female   
997   998  727-02-1313      A     Yangon       Member    Male   
998   999  347-56-2442      A     Yangon       Normal    Male   
999  1000  849-09-3807      A     Yangon       Member  Female   

             Productline  Unitprice  Quantity      Tax      Total       Date  \
995    Health and beauty      40.35         1   2.0175    42.3675  1/29/2019   
996   Home and lifestyle      97.38        10  48.6900  1022.4900   3/2/2019   
997   Food and beverages      31.84         1   1.5920    33.4320   2/9/2019   
998   Home and lifestyle      65.82         1   3.2910    69.1110  2/22/2019   
999  Fashion accessories      88.34         7  30.9190   649.2990  2/18/2019   

      Time  Payment    cogs  gross_margin_percentage  gross_iincome  Rating  
995  13:46  Ewallet   40.35                 4.7619

In [ ]:
dataframe['City']

0         Yangon
1      Naypyitaw
2         Yangon
3         Yangon
4         Yangon
         ...    
995    Naypyitaw
996     Mandalay
997       Yangon
998       Yangon
999       Yangon
Name: City, Length: 1000, dtype: object

In [ ]:
dataframe['Branch']

0      A
1      C
2      A
3      A
4      A
      ..
995    C
996    B
997    A
998    A
999    A
Name: Branch, Length: 1000, dtype: object

In [ ]:
print(dataframe['City'] , dataframe['Branch'])

0         Yangon
1      Naypyitaw
2         Yangon
3         Yangon
4         Yangon
         ...    
995    Naypyitaw
996     Mandalay
997       Yangon
998       Yangon
999       Yangon
Name: City, Length: 1000, dtype: object 0      A
1      C
2      A
3      A
4      A
      ..
995    C
996    B
997    A
998    A
999    A
Name: Branch, Length: 1000, dtype: object


In [ ]:
print(dataframe.index)

RangeIndex(start=0, stop=1000, step=1)


In [ ]:
for i in dataframe.index:
  print(dataframe.City[i], dataframe.Branch[i])

Yangon A
Naypyitaw C
Yangon A
Yangon A
Yangon A
Naypyitaw C
Yangon A
Naypyitaw C
Yangon A
Mandalay B
Mandalay B
Mandalay B
Yangon A
Yangon A
Yangon A
Mandalay B
Yangon A
Yangon A
Yangon A
Mandalay B
Naypyitaw C
Mandalay B
Mandalay B
Yangon A
Yangon A
Yangon A
Mandalay B
Yangon A
Mandalay B
Yangon A
Mandalay B
Mandalay B
Mandalay B
Yangon A
Naypyitaw C
Naypyitaw C
Yangon A
Yangon A
Naypyitaw C
Mandalay B
Mandalay B
Naypyitaw C
Mandalay B
Naypyitaw C
Naypyitaw C
Mandalay B
Mandalay B
Mandalay B
Mandalay B
Naypyitaw C
Naypyitaw C
Yangon A
Mandalay B
Naypyitaw C
Mandalay B
Naypyitaw C
Yangon A
Yangon A
Yangon A
Naypyitaw C
Naypyitaw C
Naypyitaw C
Mandalay B
Yangon A
Mandalay B
Yangon A
Naypyitaw C
Mandalay B
Yangon A
Yangon A
Naypyitaw C
Naypyitaw C
Mandalay B
Naypyitaw C
Yangon A
Naypyitaw C
Naypyitaw C
Yangon A
Naypyitaw C
Naypyitaw C
Naypyitaw C
Mandalay B
Naypyitaw C
Naypyitaw C
Naypyitaw C
Naypyitaw C
Naypyitaw C
Yangon A
Yangon A
Mandalay B
Naypyitaw C
Naypyitaw C
Yangon A
Mandalay B

In [1]:
import pandas

In [2]:
from google.colab import files
supermarket=files.upload()


Saving Supermarket_sales.csv to Supermarket_sales.csv


In [3]:
import pandas
dataframe=pandas.read_csv("Supermarket_sales.csv")
print(dataframe)

       No    InvoiceID Branch       City Customertype  Gender  \
0       1  750-67-8428      A     Yangon       Member  Female   
1       2  226-31-3081      C  Naypyitaw       Normal  Female   
2       3  631-41-3108      A     Yangon       Normal    Male   
3       4  123-19-1176      A     Yangon       Member    Male   
4       5  373-73-7910      A     Yangon       Normal    Male   
..    ...          ...    ...        ...          ...     ...   
995   996  233-67-5758      C  Naypyitaw       Normal    Male   
996   997  303-96-2227      B   Mandalay       Normal  Female   
997   998  727-02-1313      A     Yangon       Member    Male   
998   999  347-56-2442      A     Yangon       Normal    Male   
999  1000  849-09-3807      A     Yangon       Member  Female   

                Productline  Unitprice  Quantity      Tax      Total  \
0         Health and beauty      74.69         7  26.1415   548.9715   
1    Electronic accessories      15.28         5   3.8200    80.2200   
2  

In [8]:
print(dataframe.head(10))

   No    InvoiceID Branch       City Customertype  Gender  \
0   1  750-67-8428      A     Yangon       Member  Female   
1   2  226-31-3081      C  Naypyitaw       Normal  Female   
2   3  631-41-3108      A     Yangon       Normal    Male   
3   4  123-19-1176      A     Yangon       Member    Male   
4   5  373-73-7910      A     Yangon       Normal    Male   
5   6  699-14-3026      C  Naypyitaw       Normal    Male   
6   7  355-53-5943      A     Yangon       Member  Female   
7   8  315-22-5665      C  Naypyitaw       Normal  Female   
8   9  665-32-9167      A     Yangon       Member  Female   
9  10  692-92-5582      B   Mandalay       Member  Female   

              Productline  Unitprice  Quantity      Tax     Total       Date  \
0       Health and beauty      74.69         7  26.1415  548.9715   1/5/2019   
1  Electronic accessories      15.28         5   3.8200   80.2200   3/8/2019   
2      Home and lifestyle      46.33         7  16.2155  340.5255   3/3/2019   
3       

In [9]:
print(dataframe.tail(10))

       No    InvoiceID Branch       City Customertype  Gender  \
990   991  886-18-2897      A     Yangon       Normal  Female   
991   992  602-16-6955      B   Mandalay       Normal  Female   
992   993  745-74-0715      A     Yangon       Normal    Male   
993   994  690-01-6631      B   Mandalay       Normal    Male   
994   995  652-49-6720      C  Naypyitaw       Member  Female   
995   996  233-67-5758      C  Naypyitaw       Normal    Male   
996   997  303-96-2227      B   Mandalay       Normal  Female   
997   998  727-02-1313      A     Yangon       Member    Male   
998   999  347-56-2442      A     Yangon       Normal    Male   
999  1000  849-09-3807      A     Yangon       Member  Female   

                Productline  Unitprice  Quantity      Tax      Total  \
990      Food and beverages      56.56         5  14.1400   296.9400   
991       Sports and travel      76.60        10  38.3000   804.3000   
992  Electronic accessories      58.03         2   5.8030   121.8630

In [11]:
print(dataframe.loc[1])

No                                              2
InvoiceID                             226-31-3081
Branch                                          C
City                                    Naypyitaw
Customertype                               Normal
Gender                                     Female
Productline                Electronic accessories
Unitprice                                   15.28
Quantity                                        5
Tax                                          3.82
Total                                       80.22
Date                                     3/8/2019
Time                                        10:29
Payment                                      Cash
cogs                                         76.4
gross_margin_percentage                  4.761905
gross_iincome                                3.82
Rating                                        9.6
Name: 1, dtype: object


In [12]:
print(dataframe.loc[4])

No                                         5
InvoiceID                        373-73-7910
Branch                                     A
City                                  Yangon
Customertype                          Normal
Gender                                  Male
Productline                Sports and travel
Unitprice                              86.31
Quantity                                   7
Tax                                  30.2085
Total                               634.3785
Date                                2/8/2019
Time                                   10:37
Payment                              Ewallet
cogs                                  604.17
gross_margin_percentage             4.761905
gross_iincome                        30.2085
Rating                                   5.3
Name: 4, dtype: object


In [14]:
dataframe['City']

0         Yangon
1      Naypyitaw
2         Yangon
3         Yangon
4         Yangon
         ...    
995    Naypyitaw
996     Mandalay
997       Yangon
998       Yangon
999       Yangon
Name: City, Length: 1000, dtype: object

In [17]:
print(dataframe['City'] , dataframe['Branch'])

0         Yangon
1      Naypyitaw
2         Yangon
3         Yangon
4         Yangon
         ...    
995    Naypyitaw
996     Mandalay
997       Yangon
998       Yangon
999       Yangon
Name: City, Length: 1000, dtype: object 0      A
1      C
2      A
3      A
4      A
      ..
995    C
996    B
997    A
998    A
999    A
Name: Branch, Length: 1000, dtype: object


In [21]:
dataframe=dataframe.drop(['Tax'],axis=1)
dataframe.head(4)

No    InvoiceID Branch       City Customertype  Gender  \
0   1  750-67-8428      A     Yangon       Member  Female   
1   2  226-31-3081      C  Naypyitaw       Normal  Female   
2   3  631-41-3108      A     Yangon       Normal    Male   
3   4  123-19-1176      A     Yangon       Member    Male   

              Productline  Unitprice  Quantity     Total       Date   Time  \
0       Health and beauty      74.69         7  548.9715   1/5/2019  13:08   
1  Electronic accessories      15.28         5   80.2200   3/8/2019  10:29   
2      Home and lifestyle      46.33         7  340.5255   3/3/2019  13:23   
3       Health and beauty      58.22         8  489.0480  1/27/2019  20:33   

       Payment    cogs  gross_margin_percentage  gross_iincome  Rating  
0      Ewallet  522.83                 4.761905        26.1415     9.1  
1         Cash   76.40                 4.761905         3.8200     9.6  
2  Credit card  324.31                 4.761905        16.2155     7.4  
3      Ewallet  465.76                 4.761905        23.2880     8.4

In [24]:
print (dataframe.head(2))
dataframe.drop([5],axis=0)
print("****")

   No    InvoiceID Branch       City Customertype  Gender  \
0   1  750-67-8428      A     Yangon       Member  Female   
1   2  226-31-3081      C  Naypyitaw       Normal  Female   

              Productline  Unitprice  Quantity     Total      Date   Time  \
0       Health and beauty      74.69         7  548.9715  1/5/2019  13:08   
1  Electronic accessories      15.28         5   80.2200  3/8/2019  10:29   

   Payment    cogs  gross_margin_percentage  gross_iincome  Rating  
0  Ewallet  522.83                 4.761905        26.1415     9.1  
1     Cash   76.40                 4.761905         3.8200     9.6  
****


In [28]:
dataframe=pandas.read_csv("Supermarket_sales.csv")
max_overall= dataframe.Unitprice.idxmax()
print(max_overall)

122


In [29]:
min_age=dataframe.age.min()
min_age_loc = dataframe.age.idxmin()
min_age=dataframe.loc[min_age]

AttributeError: ignored

In [34]:
dataframe.loc[dataframe["Customertype"]=="Normal"]

No    InvoiceID Branch       City Customertype  Gender  \
1      2  226-31-3081      C  Naypyitaw       Normal  Female   
2      3  631-41-3108      A     Yangon       Normal    Male   
4      5  373-73-7910      A     Yangon       Normal    Male   
5      6  699-14-3026      C  Naypyitaw       Normal    Male   
7      8  315-22-5665      C  Naypyitaw       Normal  Female   
..   ...          ...    ...        ...          ...     ...   
992  993  745-74-0715      A     Yangon       Normal    Male   
993  994  690-01-6631      B   Mandalay       Normal    Male   
995  996  233-67-5758      C  Naypyitaw       Normal    Male   
996  997  303-96-2227      B   Mandalay       Normal  Female   
998  999  347-56-2442      A     Yangon       Normal    Male   

                Productline  Unitprice  Quantity      Tax      Total  \
1    Electronic accessories      15.28         5   3.8200    80.2200   
2        Home and lifestyle      46.33         7  16.2155   340.5255   
4         Sports and travel      86.31         7  30.2085   634.3785   
5    Electronic accessories      85.39         7  29.8865   627.6165   
7        Home and lifestyle      73.56        10  36.7800   772.3800   
..                      ...        ...       ...      ...        ...   
992  Electronic accessories      58.03         2   5.8030   121.8630   
993     Fashion accessories      17.49        10   8.7450   183.6450   
995       Health and beauty      40.35         1   2.0175    42.3675   
996      Home and lifestyle      97.38        10  48.6900  1022.4900   
998      Home and lifestyle      65.82         1   3.2910    69.1110   

          Date   Time      Payment    cogs  gross_margin_percentage  \
1     3/8/2019  10:29         Cash   76.40                 4.761905   
2     3/3/2019  13:23  Credit card  324.31                 4.761905   
4     2/8/2019  10:37      Ewallet  604.17                 4.761905   
5    3/25/2019  18:30      Ewallet  597.73                 4.761905   
7    2/24/2019  11:38      Ewallet  735.60                 4.761905   
..         ...    ...          ...     ...                      ...   
992  3/10/2019  20:46      Ewallet  116.06                 4.761905   
993  2/22/2019  18:35      Ewallet  174.90                 4.761905   
995  1/29/2019  13:46      Ewallet   40.35                 4.761905   
996   3/2/2019  17:16      Ewallet  973.80                 4.761905   
998  2/22/2019  15:33         Cash   65.82                 4.761905   

     gross_iincome  Rating  
1           3.8200     9.6  
2          16.2155     7.4  
4          30.2085     5.3  
5          29.8865     4.1  
7          36.7800     8.0  
..             ...     ...  
992         5.8030     8.8  
993         8.7450     6.6  
995         2.0175     6.2  
996        48.6900     4.4  
998         3.2910     4.1  

[499 rows x 18 columns]

In [38]:
import numpy as np
student_marks_BA=[12, 14,10]
Marksarray=np.array(student_marks_BA)
print(Marksarray)

[12 14 10]


In [43]:
student_marks_BA=[[12,14,10], [15,19,20],[11,15,19]]
marksarray=np.array(student_marks_BA)
print(marksarray)

[[12 14 10]
 [15 19 20]
 [11 15 19]]


In [44]:
values1=np.arange(20)
print(values1)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [47]:
values=np.arange(1,11)
print(values)

[ 1  2  3  4  5  6  7  8  9 10]


In [48]:
values=np.arange(50,60)
print(values)

[50 51 52 53 54 55 56 57 58 59]


In [50]:
zeroarray = np.zeros(8)
print(zeroarray)

[0. 0. 0. 0. 0. 0. 0. 0.]


In [52]:
zeroarray = np.zeros((2,6))
print(zeroarray)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [53]:
onesarray = np.ones(6)
print(onesarray)

[1. 1. 1. 1. 1. 1.]


In [55]:
onesarray = np.ones((8,2))
print(onesarray)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [56]:
identityarray=np.eye(5)
print(identityarray)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [57]:
len(zeroarray)

2

In [59]:
len(onesarray)

8

In [67]:
firstarray=np.array([[10,14,10,50], [15,19,13,20],[11,15,11,19]])
print(firstarray.shape)
secondarray=firstarray.reshape(4,3)
print(firstarray)

(3, 4)
[[10 14 10 50]
 [15 19 13 20]
 [11 15 11 19]]


In [68]:
values=np.random.randint(1,3,5)
print(values)


[2 1 2 2 2]


In [70]:
values=np.random.randint(44,88,6)
print(values)

[60 65 62 86 71 51]


In [72]:
randshaped = np.random.randint(25,50,(5,3))
print(randshaped)

[[46 38 47]
 [30 35 41]
 [32 26 39]
 [43 28 30]
 [41 42 32]]
